### ISSUE TITLE
feat: output_attentions

### ISSUE THREAD

**Issue by xloem** [AminRezaei0x443/memory-efficient-attention#1]
I'm looking into hacking some of the models in the transformers library to use this library for attention, and I don't see a way to support `output_attentions` yet.  This is a flag passed in transformers, where the attention weights are preserved and returned to the user, if it is set.

I looked a little at implementing this in the torch backend, and I note the scan() function provides for only a single tensor return value. It seems to me that scan() function would be most clearly replaced by a for loop, but it could also be modified to handle tuples, or return_weights could be handled via accessing nonlocal data in some way instead of returning them through the chunk scanner. I'm also not sure how the output would best be passed to the user.

Edit: Draft implementation 01/28 at https://github.com/AminRezaei0x443/memory-efficient-attention/compare/main...xloem:faba6371ac7faaa2040a2c26e15ae7ab87f94ce4 . I ended up extending the scan function for parity between implementations.
Edit 2: Turns out it's the postsoftmax attention weights, not the presoftmax attention weights. I've updated this post and the draft implementation for this output: https://github.com/AminRezaei0x443/memory-efficient-attention/compare/main...xloem:return_weights

**Comment by xloem** [comment]
I see for this to have any meaning it would need to be implemented as either a callback or only retaining a user-provided range, and I don't imagine that use cases provided for that yet. Apologies for the noise and thank you for so much great work.

**Comment by AminRezaei0x443** [comment]
Hi, Thanks for your concerns and implementation. Also, I'm sorry about reaching out late. 
Yeah, you're right; Returning those intermediate weights raises the memory back to O(n^2). 
You know, the big deal here is the use case for this attention implementation. According to the paper, memory reduction is not significant unless your sequence length is >= 2^14 = 16384. In most models and approaches, this length is not common.
So If you need complete intermediate weights, using other attention mechanisms which reduce the order by approximation and not chunking, would be more ideal in my opinion. Unless you need to operate on chunked intermediate weights which can be implemented as a callable function without increasing the memory complexity.
Also remember that, as the current implementation is receiving full masks as input, If you use masks or biases it will anyway be O(n^2).

**Comment by xloem** [comment]
Thanks, I didn't think about the masks (or know about other approaches). I'm thinking your code could be changed to accept unexpanded masks.

**Comment by AminRezaei0x443** [comment]
Yes, the masks and biases should be either unexpanded or calculated just per chunk indices so the memory complexity doesn't increase.
